---
title: "Overdose crisis data - EDA"
author: "Nayef Ahmad"
date: "8/22/2020"
output: 
  html_document: 
    keep_md: yes
    code_folding: hide
    toc: true
    toc_float:
      collapsed: false
    toc_folding: false
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE, warning = FALSE)
```

# Libraries 
```{r}
library(tidyverse)
library(here)
```

# Overview 



# Wide data 
```{r}
df1_raw <- read_csv(here::here("data", "ScopingReviewOfOpioi-FinalResults_DATA_2020-07-06_1942.csv"))

nrow(df1_raw)
# str(df1_raw)
names(df1_raw)
```

## Data wrangling
```{r}
df2_clean <- 
    df1_raw %>% 
    mutate(country_income_check = country_income___1 + 
               country_income___2 + 
               country_income___3 + 
               country_income___4
           )

df2_clean %>% 
    filter(country_yn == 1) %>% 
    count(country_income_check)

```


## Counts 
```{r}
table(df1_raw$country_yn)
df1_raw %>% count(country)
```


# Long data 
```{r}
df3_long_raw_01 <- read_csv(here("data",
                                 "outfile_policies_impacts_20200712.csv"))

df4_long_raw_02 <- read_csv(here("data",
                                 "outfile_remaining_vars_2020_07_13.csv"))

names(df3_long_raw_01)
names(df4_long_raw_02)
```


# Questions 
1. What does 9090 represent in colnames? 